name: C++ Windows Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MinGW
      run: |
        choco install mingw -y
        echo "::add-path::C:\\tools\\mingw64\\bin"

    - name: Install GLFW Dependencies
      run: |
        curl -L https://github.com/glfw/glfw/releases/download/3.3.4/glfw-3.3.4.bin.WIN64.zip --output glfw.zip
        tar -xf glfw.zip
        mkdir -p glfw/include
        mkdir -p glfw/src
        xcopy glfw-3.3.4.bin.WIN64/include glfw/include /E /Q
        xcopy glfw-3.3.4.bin.WIN64/lib-mingw-w64 glfw/src /E /Q

    - name: Compile Resource File and Application
      run: |
        windres mbg.rc -o mbg_res.o
        g++ -Iglfw/include -Iimgui -Iimgui/backends mbg.cpp mbg_imgui_with_keys.cpp imgui/imgui.cpp imgui/imgui_draw.cpp imgui/imgui_tables.cpp imgui/imgui_widgets.cpp imgui/backends/imgui_impl_glfw.cpp imgui/backends/imgui_impl_opengl3.cpp mbg_res.o -o MacroBubbleGum.exe -Lglfw/src -lglfw3 -lgdi32 -lopengl32 -static -mwindows

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MacroBubbleGum
        path: MacroBubbleGum.exe
