name: C++ Windows Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download and Setup MinGW
      run: |
        curl -L https://sourceforge.net/projects/mingw-w64/files/latest/download -o mingw.zip
        tar -xf mingw.zip --directory C:/mingw64 --strip-components=1
        echo "C:/mingw64/bin" >> $GITHUB_ENV

    - name: Download ImGui
      run: |
        curl -L https://github.com/ocornut/imgui/archive/refs/heads/master.zip --output imgui.zip
        tar -xf imgui.zip
        mv imgui-master imgui

    - name: Install GLFW Dependencies
      run: |
        curl -L https://github.com/glfw/glfw/releases/download/3.3.4/glfw-3.3.4.bin.WIN64.zip --output glfw.zip
        tar -xf glfw.zip
        if (!(Test-Path -Path glfw\include)) { New-Item -ItemType Directory -Path glfw\include }
        if (!(Test-Path -Path glfw\src)) { New-Item -ItemType Directory -Path glfw\src }
        xcopy glfw-3.3.4.bin.WIN64\include glfw\include /E /I /Q
        xcopy glfw-3.3.4.bin.WIN64\lib-mingw-w64 glfw\src /E /I /Q

    - name: Compile Resource File and Application
      run: |
        windres mbg.rc -o mbg_res.o
        g++ -Iglfw/include -Iimgui -Iimgui/backends mbg.cpp mbg_imgui_with_keys.cpp imgui/imgui.cpp imgui/imgui_draw.cpp imgui/imgui_tables.cpp imgui/imgui_widgets.cpp imgui/backends/imgui_impl_glfw.cpp imgui/backends/imgui_impl_opengl3.cpp mbg_res.o -o MacroBubbleGum.exe -Lglfw/src -lglfw3 -lgdi32 -lopengl32 -static -mwindows

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MacroBubbleGum
        path: MacroBubbleGum.exe
