
name: C++ ImGui Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup C++ Compiler on Windows
      run: choco install mingw

    - name: Install Dependencies (GLFW)
      run: |
        git clone https://github.com/glfw/glfw.git
        cd glfw
        cmake -G "MinGW Makefiles" .
        mingw32-make
        cd ..

    - name: Install Dependencies (ImGui)
      run: |
        git clone https://github.com/ocornut/imgui.git
        cd imgui
        git clone https://github.com/ocornut/imgui.git
        cd imgui/backends
        git clone https://github.com/glfw/glfw.git
        cd ../..

    - name: Compile the Code with ImGui and GLFW
      run: |
        g++ -Iglfw/include -Iimgui -Iimgui/backends ./input_simulator_imgui.cpp -o input_simulator.exe -Lglfw/src -lglfw3 -lgdi32 -lopengl32 -static

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v3
      with:
        name: input_simulator_imgui_windows
        path: ./input_simulator.exe
