
name: C++ Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup C++ Compiler on Windows
      run: choco install mingw

    - name: Compile the Code
      run: |
        g++ input_simulator.cpp -o input_simulator.exe

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: input_simulator_windows
        path: ./input_simulator.exe
