name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup C++ Compiler on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install g++ -y

    - name: Setup C++ Compiler on Windows
      if: matrix.os == 'windows-latest'
      run: choco install mingw

    - name: Setup C++ Compiler on macOS
      if: matrix.os == 'macos-latest'
      run: brew install gcc

    - name: Compile the Code
      run: |
        g++ input_simulator.cpp -o input_simulator
        ./input_simulator
